### ISSUE TITLE
About mdx  support

### ISSUE THREAD

**Issue by unix** [egoist/docup#14]
Hi, @egoist , thank you for continuously creating  high quality OSS, `docup` looks easy to use.

Is it possible for `docup` to support `.mdx` document in the future?

**Comment by egoist** [comment]
If you don't mind a build step, yes we can support that.

**Comment by egoist** [comment]
But before that you can already use Preact components in your Markdown file: https://docup.now.sh/#inline-component

**Comment by unix** [comment]
Um, Preact component is exactly what I need.
