### ISSUE TITLE
Use throttle instead of debounce

### ISSUE THREAD

**Issue by estevanmaito** [egoist/docup#17]
When scrolling, the current behavior looks _laggy_ because debounce actually only fires after 200ms have passed since the last scroll.

Using throttle, with the same 200ms delay, it would fire **every** 200ms.

It would still avoid performance problems, but give a more instant feedback (you could even make it fire every 100ms).

I'm talking about this line https://github.com/egoist/docup/blob/master/src/components/App.tsx#L12

Here's an example of the behavior of debounce and throttle https://codepen.io/chriscoyier/pen/vOZNQV

**Comment by egoist** [comment]
You're right, mind sending a PR?

**Comment by estevanmaito** [comment]
Yeah, I'll try it tonight.

**Comment by egoist** [comment]
@estevanmaito thanks I got some time so I think I might just fix it 😄

**Comment by estevanmaito** [comment]
I've just finished `npm install` 😅

Just saw it live, looks great!
