### ISSUE TITLE
Easier "Google-able" name instead of docup?

### ISSUE THREAD

**Issue by aravindhsampath** [egoist/docup#5]
Really cool project that does one thing well. Thanks! 
However, would it be nice to have a name that is easier to Google and is not the same as another npm package or a document management company in India?
[Image](https://imgur.com/a/EzSAk)
Just my two cents.

**Comment by egoist** [comment]
Hmm any good suggestions? 😄

**Comment by aravindhsampath** [comment]
I usually spend a few minutes clicking on this: http://online-generator.com/name-generator/product-name-generator.php
to get some weird names for my pet projects.

**Comment by egoist** [comment]
Closing since naming is too hard 😅
